//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csm.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ParamsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParamsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csm.Business.ParamsResources", typeof(ParamsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Border Width.
        /// </summary>
        internal static string border_desc {
            get {
                return ResourceManager.GetString("border_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The border width around an image. The border will be black..
        /// </summary>
        internal static string border_note {
            get {
                return ResourceManager.GetString("border_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover File.
        /// </summary>
        internal static string cfile_desc {
            get {
                return ResourceManager.GetString("cfile_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file to use as the cover. (Changing this option reloads the file list)..
        /// </summary>
        internal static string cfile_note {
            get {
                return ResourceManager.GetString("cfile_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to Fill Cover Gaps.
        /// </summary>
        internal static string cfill_desc {
            get {
                return ResourceManager.GetString("cfill_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill any gaps on the sides of the cover with thumbnails; moves the cover to the left side..
        /// </summary>
        internal static string cfill_note {
            get {
                return ResourceManager.GetString("cfill_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum cover width.
        /// </summary>
        internal static string cmaxw_desc {
            get {
                return ResourceManager.GetString("cmaxw_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum percentage of the sheet width that the cover&apos;s width can be (approximate).
        /// </summary>
        internal static string cmaxw_note {
            get {
                return ResourceManager.GetString("cmaxw_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Images per Row.
        /// </summary>
        internal static string cols_desc {
            get {
                return ResourceManager.GetString("cols_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of images per row. Rows with mixed aspect ratios will probably have fewer images..
        /// </summary>
        internal static string cols_note {
            get {
                return ResourceManager.GetString("cols_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cover.
        /// </summary>
        internal static string cover_desc {
            get {
                return ResourceManager.GetString("cover_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a cover at the top of the sheet. (Changing this option reloads the file list)..
        /// </summary>
        internal static string cover_note {
            get {
                return ResourceManager.GetString("cover_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Pattern.
        /// </summary>
        internal static string cregx_desc {
            get {
                return ResourceManager.GetString("cregx_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary regular expression used to match cover files. (Changing this option reloads the file list)..
        /// </summary>
        internal static string cregx_note {
            get {
                return ResourceManager.GetString("cregx_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit on Complete.
        /// </summary>
        internal static string exit_desc {
            get {
                return ResourceManager.GetString("exit_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the GUI when the sheet is finished. Doesn&apos;t apply to the command-line..
        /// </summary>
        internal static string exit_note {
            get {
                return ResourceManager.GetString("exit_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Pattern.
        /// </summary>
        internal static string fregx_desc {
            get {
                return ResourceManager.GetString("fregx_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A regular expression used to match on file names to be included from the source..
        /// </summary>
        internal static string fregx_note {
            get {
                return ResourceManager.GetString("fregx_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Header.
        /// </summary>
        internal static string hbold_desc {
            get {
                return ResourceManager.GetString("hbold_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes the header text bold..
        /// </summary>
        internal static string hbold_note {
            get {
                return ResourceManager.GetString("hbold_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Header.
        /// </summary>
        internal static string header_desc {
            get {
                return ResourceManager.GetString("header_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the title of the sheet and other info at the top of the sheet..
        /// </summary>
        internal static string header_note {
            get {
                return ResourceManager.GetString("header_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Font Size.
        /// </summary>
        internal static string hsize_desc {
            get {
                return ResourceManager.GetString("hsize_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size of the header text..
        /// </summary>
        internal static string hsize_note {
            get {
                return ResourceManager.GetString("hsize_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Statistics.
        /// </summary>
        internal static string hstats_desc {
            get {
                return ResourceManager.GetString("hstats_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics about the images, e.g. &quot;(x100) max 1200x600px&quot;..
        /// </summary>
        internal static string hstats_note {
            get {
                return ResourceManager.GetString("hstats_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Title.
        /// </summary>
        internal static string htitle_desc {
            get {
                return ResourceManager.GetString("htitle_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the image set..
        /// </summary>
        internal static string htitle_note {
            get {
                return ResourceManager.GetString("htitle_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image count and maximum image dimensions..
        /// </summary>
        internal static string htstats_note {
            get {
                return ResourceManager.GetString("htstats_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Image Labels.
        /// </summary>
        internal static string labels_desc {
            get {
                return ResourceManager.GetString("labels_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the filename for each image..
        /// </summary>
        internal static string labels_note {
            get {
                return ResourceManager.GetString("labels_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Label Font Size.
        /// </summary>
        internal static string lsize_desc {
            get {
                return ResourceManager.GetString("lsize_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font size of the image label text..
        /// </summary>
        internal static string lsize_note {
            get {
                return ResourceManager.GetString("lsize_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Random Images.
        /// </summary>
        internal static string maxrand_desc {
            get {
                return ResourceManager.GetString("maxrand_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If more than 0, only up to this many images (randomly selected) will be included in the output..
        /// </summary>
        internal static string maxrand_note {
            get {
                return ResourceManager.GetString("maxrand_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Thumbnail Dimension (Height and Width).
        /// </summary>
        internal static string mindim_desc {
            get {
                return ResourceManager.GetString("mindim_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All thumbnails&apos; widths and heights will be at least this value..
        /// </summary>
        internal static string mindim_note {
            get {
                return ResourceManager.GetString("mindim_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Input Dimension (Height and Width).
        /// </summary>
        internal static string mindiminput_desc {
            get {
                return ResourceManager.GetString("mindiminput_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum width and height for input images to be included in the output sheet. (Changing this option reloads the file list)..
        /// </summary>
        internal static string mindiminput_note {
            get {
                return ResourceManager.GetString("mindiminput_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Launch GUI.
        /// </summary>
        internal static string nogui_desc {
            get {
                return ResourceManager.GetString("nogui_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents the GUI (Graphical User Interface) from being launched..
        /// </summary>
        internal static string nogui_note {
            get {
                return ResourceManager.GetString("nogui_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Output Directory on Complete.
        /// </summary>
        internal static string openoutdir_desc {
            get {
                return ResourceManager.GetString("openoutdir_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the output directory in Windows Explorer when completed (GUI mode only)..
        /// </summary>
        internal static string openoutdir_note {
            get {
                return ResourceManager.GetString("openoutdir_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string outfile_desc {
            get {
                return ResourceManager.GetString("outfile_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name or path of the output contact sheet file. Path can be absolute or relative to the source&apos;s parent directory. Use {title} to include the header title in the file name. (Changing this option reloads the file list)..
        /// </summary>
        internal static string outfile_note {
            get {
                return ResourceManager.GetString("outfile_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Layout Only.
        /// </summary>
        internal static string preview_desc {
            get {
                return ResourceManager.GetString("preview_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only draw the layout, not the images. Near instantaneous..
        /// </summary>
        internal static string preview_note {
            get {
                return ResourceManager.GetString("preview_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Quality.
        /// </summary>
        internal static string qual_desc {
            get {
                return ResourceManager.GetString("qual_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Jpeg compression quality of the output image..
        /// </summary>
        internal static string qual_note {
            get {
                return ResourceManager.GetString("qual_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Shift Buffer.
        /// </summary>
        internal static string shiftbuffer_desc {
            get {
                return ResourceManager.GetString("shiftbuffer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of the &quot;max row height&quot; to consider as a buffer for determining if an outlier row height is too tall and requires adjustment. Smaller values will result in more uniform row heights, but large values may result in more interesting row layouts..
        /// </summary>
        internal static string shiftbuffer_note {
            get {
                return ResourceManager.GetString("shiftbuffer_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of Contact Sheet.
        /// </summary>
        internal static string width_desc {
            get {
                return ResourceManager.GetString("width_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the contact sheet in pixels..
        /// </summary>
        internal static string width_note {
            get {
                return ResourceManager.GetString("width_note", resourceCulture);
            }
        }
    }
}
