name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name_gui="csm-$tag-${{ matrix.target }}-gui"
          release_name_cmd="csm-$tag-${{ matrix.target }}-cmd"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Only Build WinForms project
            dotnet publish csm.WinForms/csm.WinForms.csproj --framework net6.0-windows --runtime "${{ matrix.target }}" --no-self-contained -c Release -o "$release_name_gui"
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
            # Delete output directory
            rm -r "$release_name_gui"
          fi
          dotnet publish csm.Console/csm.Console.csproj --framework net6.0 --runtime "${{ matrix.target }}" --no-self-contained -c Release -o "$release_name_cmd"
          tar czvf "${release_name}.tar.gz" "$release_name_cmd"
          # Delete output directory
          rm -r "$release_name_cmd"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "csm-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}